config/routes.rb
Rails.application.routes.draw do
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  resources :users, only: %i[show index update] do
    patch 'contents', to: 'contents#position_update'
    resources :contents, param: :position, only: %i[edit update]
  end
  delete '/logout', to: 'oauths#destroy'
  get '/terms', to: 'user_sessions#terms'
  root 'user_sessions#login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  attr_accessor :user_id, :provider, :uid
  belongs_to :user
end

app/models/content.rb
class Content < ApplicationRecord
  include Rails.application.routes.url_helpers
  belongs_to :user
  validates_presence_of :position

  def content_img
    amazon_img.present? ? amazon_img : '/images/no_photo.jpg'
  end

  def create_link
    amazon_link.present? ? amazon_link : edit_user_content_path(user_id, position)
  end
end

app/models/search_item.rb
class Search_item
  # プロパティの設定
  attr_accessor :title, :image_url, :url

  def initialize(title, image_url, url)
    @title = title
    @image_url = image_url
    @url = url
  end

  def update_params
    { amazon_img: "#{image_url}",
      amazon_link: "#{url}" }
  end

  def search_image_set
    image_url.present? ? image_url : 'no_photo.jpg'
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end
  has_many :authentications, dependent: :destroy
  has_many :contents, dependent: :destroy
  accepts_nested_attributes_for :authentications
  validates :title, length: { maximum: 25 }
  validates_presence_of :name, :twitter_id, :twitter_url, :title
  validates :twitter_id, uniqueness: true

  def portfolio_creator?(current_user)
    # ユニークキーでの比較を実施
    self.twitter_id == current_user.twitter_id if current_user.present?
  end

  def twitter_user_info_updated?(twitter_user)
    name != twitter_user.name || twitter_icon != twitter_user.twitter_icon || twitter_url != twitter_user.twitter_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/concerns/amazon_search_module.rb
module AmazonSearchModule
  extend ActiveSupport::Concern

  def search_item_from_amazon(search_word)
    search_results = []
    return search_results if search_word.blank?
    # デバックログ出力オン
    Amazon::Ecs.debug = true
    # Amazon::Ecs::Responseオブジェクトの取得
    amazon_items = search_option(search_word)
    # 商品のタイトル,画像URL, 詳細ページURLの取得
    search_results = get_item_detail(amazon_items)
  end

  def search_option(search_word)
    Amazon::Ecs.item_search(
      search_word,
      search_index:  'All',
      dataType: 'script',
      response_group: 'ItemAttributes, Images',
      country:  'jp',
    )
  end

  def get_item_detail(results)
    search_item_details = []
    results.items.each do |item|
      result = Search_item.new(
        item.get('ItemAttributes/Title'),
        item.get('LargeImage/URL'),
        item.get('DetailPageURL'),
      )
      search_item_details << result
    end
    search_item_details
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  include AmazonSearchModule
  before_action :set_content, only: %i[edit update]
  before_action :authentication_check, only: %i[edit update position_update]

  def edit
    @results = search_item_from_amazon(params[:keyword])
  end

  def update
    if @content.update(content_params)
      redirect_to user_path(current_user), success: '商品を設定しました'
    else
      flash.now[:danger] = '商品が設定できませんでした'
      render :edit
    end
  end

  def position_update
    @user = User.find(params[:user_id])
    positions = params[:positions].map(&:to_i)
    @contents = @user.contents.order(:position)
    move_contents = []
    @contents.each.with_index(1) do |content, i|
      if positions[i] != content.position
        content.position = positions[i]
        move_contents << content
      end
    end
    @contents.import move_contents, on_duplicate_key_update: [:position]
    render json: positions
  end

    private
      def content_params
        params.permit(
          :amazon_img,
          :amazon_link
        )
      end

      def set_content
        @content = Content.find_by(user_id: params[:user_id], position: params[:position])
      end

      def authentication_check
        # 編集ページは作成者以外見れないように作成者IDとユーザIDをチェック
        redirect_to user_path(params[:user_id]), danger: '商品は作成者以外設定できません' unless logged_in? && current_user.id == params[:user_id].to_i
      end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  def oauth
    login_at(params[:provider])
  end

  def callback
    twitter_access_denied && return  if params[:denied].present?
    @user = login_from(params[:provider])
    # この時点でuser_attrs(@provider.user_info_mapping, @user_hash)にDBに必要なTwitter上のユーザー情報が入っている
    user_params = user_attrs(@provider.user_info_mapping, @user_hash)
    # 更に画像を大きくしたい場合、gsubの第２引数を""にするとオリジナルサイズを取得可能
    user_params[:twitter_icon] = user_params[:twitter_icon].gsub("_normal", "_bigger")
    @user = User.find_by(twitter_id: user_params[:twitter_id])
    if @user
      @twitter_user = User.new(user_params)
      @user.update(user_params) if @user.twitter_user_info_updated?(@twitter_user)
    else
      @user = User.new(user_params)
      # ユーザーに紐づくコンテンツを9個生成
      (1..9).each { |n| @user.contents.build(position: n) }
      @user.save
    end
    auto_login(@user)
    redirect_to user_path(@user), success: 'ログインしました'
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトしました'
  end

  private
    def twitter_access_denied
      redirect_to root_path, danger: 'ログインできませんでした'
      return true
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def login
  end

  def terms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  PER = 30

  def show
    @contents = @user.contents.order(position: :asc) if @user
  end

  def index
    # 最新の登録コンテンツをユーザー毎に取得
    @contents = Content.order(updated_at: :desc).to_a.uniq { |c| c.user_id }
    @contents_all = Kaminari.paginate_array(@contents).page(params[:page]).per(PER)
  end

  def update
    if current_user.update(user_params)
      render json: current_user
    else
      render json: { errors: current_user.errors.messages }, status: 422
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :title
      )
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sns_account_link(user_twitter_url)
    "https://twitter.com/#{user_twitter_url}"
  end

  def sns_share_text(user)
    if user == current_user
      "#{user.title}を公開します！"
    else
      "#{user.name}さんの『#{user.title}』がすごい！"
    end
  end

  def current_page
    "#{url_for(only_path: false)}"
  end
end

app/views/contents/_search_result.html.slim
- if @results.present?
  - @results.each do |result|
    .search-result
      = link_to image_tag(result.search_image_set, class: "search_result"),
      user_content_path(result.update_params),
                        method: :patch
      .search-title
        p = result.title

app/views/contents/edit.html.slim
.main
  .alert.alert-danger.alert-dismissable
    button.close type="button"  data-dismiss="alert" aria-hidden="true" ×
    b この機能は現在停止中です。
  .search-intro
    p 設定したい商品名を検索ボックスに入力して検索しよう
    p 検索結果から設定したい商品の画像をクリックしよう
  /*= form_tag(edit_user_content_path, method: :get, id: "search-box") do */
  = form_tag("#", method: :get, id: "search-box") do
    = text_field_tag :search, "",
                      id: "search-form",
                      name: "keyword",
                      placeholder: "キーワードを入力"
    = button_tag type: 'submit', id: "search-btn", disabled: "disabled" do
      i.fa.fa-search
  #search_list
    = render partial: 'search_result'
  = javascript_include_tag "incremental_search.js"

app/views/contents/edit.js.erb
$("#search_list").html("<%= j(render 'search_result') %>");

app/views/layouts/_meta_tags.html.slim
meta name="twitter:card" content="summary_large_image"
meta name="twitter:site" content="@PORTFOL40205962"
meta property="og:url" content="#{url_for(only_path: false)}"
meta property="og:title" content="あなたの好きなものをポートフォリオ化できるサービス"
meta property="og:description" content="[portfolio]であなたの好きなものを公開してみませんか？"
meta property="og:image" content="#{asset_url('title_logo.png')}"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OriginalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title PORTFOLIO
    = render partial: 'layouts/meta_tags'
    = csrf_meta_tags
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    .header
      = render 'shared/header'
    .body
      = render 'shared/flash_message'
      = yield
      = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'
      = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js'
    .footer
      = render 'shared/footer'

app/views/shared/_flash_message.html.slim
#flash_message
  - flash.each do |message_type, message|
    div class=("alert alert-#{message_type} alert-dismissable")
      i.fa.fa-check
      button.close aria-hidden="true" data-dismiss="alert" type="button"  ×
      b= message

app/views/shared/_footer.html.slim
.footer_menu
  .terms
    = link_to '利用規約', terms_path, id: "terms"
    = link_to 'お問い合わせ', 'https://twitter.com/PORTFOL40205962', id: 'contact'

app/views/shared/_header.html.slim
.header_inner
  .header_left
    = link_to root_path do
      = image_tag 'header_logo.png', class: 'header_logo'
  .header_center
    .button
      = link_to raw("みんなの<br>ポートフォリオを見る"), users_path, class: "menu_portfolios"
  .header_right
    - if current_user.present?
      .menu
        = image_tag current_user.twitter_icon, class: 'rounded_circle'
        ul
          li
            = link_to 'マイページ', user_path(current_user)
          li
            = link_to 'ログアウト', logout_path, method: :delete
    - else
      .menu
        .login_btn
          a.btn.btn-social.btn-tw href="/oauth/twitter" role="button"
            i.fa.fa-twitter.left
            | ログイン

app/views/shared/_share_button.html.slim
script.async src="https://platform.twitter.com/widgets.js" charset="utf-8"
= link_to 'Tweet', 'https://twitter.com/share?ref_src=twsrc%5Etfw', class: 'twitter-share-button',data: { hashtags: 'portfolio', lang: 'ja', size: 'large', text: sns_share_text(@user), url: current_page, show: { count: false } }

app/views/shared/_user_template.html.slim
- if content.amazon_img.present?
tbody
  tr.text-center
    td
      = link_to sns_account_link(content.user.twitter_url), target: '_new' do
        = image_tag content.user.twitter_icon, class: 'rounded_circle'
      br
      = content.user.name
    td
      = content.user.title
    td
      = link_to user_path(content.user) do
        - image_tag content.content_img, class: 'content_index', height: "100px"

app/views/user_sessions/login.html.slim
.top_page
  .title_top
    .title_logo
      = image_tag 'title_logo', class: 'title_logo'
  .title_body
    .introduction_top
      h2 あなたの好きなものを<br>公開してみませんか？
      h8 「映画、本、食べ物、ファッションアイテム」等
      br
      h8 簡単に登録し、シェアできるサービスです！
    .introduction_body
      .introduction_img
        = image_tag 'portfolio_sample_1', class: 'portfolio_img'
        = image_tag 'portfolio_sample_2', class: 'portfolio_img'
    .introduction_footer
      h2 今すぐ使ってみよう！
      .login_btn
        a.btn.btn-social.btn-tw href="/oauth/twitter" role="button"
          i.fa.fa-twitter.left
          | Twitterでログイン

app/views/user_sessions/terms.html.slim
.main
  .row
    .col-12.col-md-8.offset-md-2
      h2
        | 利用規約
      p
        | この利用規約（以下、「本規約」といいます。）は，このウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
      h3
        | 第1条(適用)
      p
        | 本規約は、ユーザーと本サービス運営者との間の本サービスの利用に関わる一切の関係に適用されるものとします。
      h3
        | 第2条(利用登録)
      p
        | 1. 登録希望者が本サービスの定める方法によって利用登録を申請し，本サービス運営者がこれを承認することによって，利用登録が完了するものとします。
          <br>
          2. 本サービスは，TwitterAPIを利用した認証による利用登録を採用しています。本サービスの仕様上，ユーザーのTwitterアカウントが非公開アカウントの場合，本サービスの利用ができない仕様となっておりますので，あらかじめご了承ください。
      h3
        | 第3条(ユーザー情報の利用目的)
      p
        | 本サービスは，ユーザーのTwitterアカウントに関して，以下の情報を取得します。
          <br>
          (1) TwitterID(ユーザーに一意で付与される数字の羅列のデータ)(例. 99999999999999)
          <br>
          (2) Twitter上の名前
          <br>
          (3) Twitter上のユーザー名
          <br>
          以上の情報は、本サービスにおけるプロフィールとしての目的でのみ利用する情報であり，その他一切の利用を目的とするものではございませんので，安心して本サービスをご利用ください。

      h3
        | 第4条(禁止事項)
      p
        | ユーザーは、本サービスの利用にあたり，以下の行為をしてはなりません。
          <br>
          (1) 法令または公序良俗に反する行為
          <br>
          (2) 犯罪行為に関連する行為
          <br>
          (3) 本サービスのサーバーまたはネットワークの機能を破壊したり，妨害したりする行為
          <br>
          (4) 本サービスの運営を妨害するおそれのある行為
          <br>
          (5) 他のユーザーに関する個人情報等を収集または蓄積する行為
          <br>
          (6) 他のユーザーに成りすます行為
          <br>
          (7) 本サービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為
          <br>
          (8) その他，本サービスの運営者が不適切と判断する行為
      h3
        | 第5条(本サービスの提供の停止等)
      p
        | 1. 本サービスの運営者は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
          <br>
          (1) 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
          <br>
          (2) 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合
          <br>
          (3) コンピュータまたは通信回線等が事故により停止した場合
          <br>
          (4) その他，本サービスの運営者が本サービスの提供が困難と判断した場合
          <br>
          2. 本サービスの運営者は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。
      h3
        | 第6条(利用制限および登録抹消)
      p
        | 1. 本サービスの運営者は，以下の場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。
          (1) 本規約のいずれかの条項に違反した場合
          (2) その他，当社が本サービスの利用を適当でないと判断した場合
          2. 本サービスの運営者は，本条に基づき本サービスの運営者が行った行為によりユーザーに生じた損害について，一切の責任を負いません。
      h3
        | 第7条(免責事項)
      p
        | 本サービスの運営者は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。
      h3
        | 第8条(サービス内容の変更等)
      p
        | 本サービスの運営者は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
      h3
        | 第9条(利用規約の変更)
      p
        | 本サービスの運営者は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。
      h3
        | 第10条(Amazon アソシエイト・プログラムの利用)
      p
        | 本サービスはamazon.co.jpを宣伝しリンクすることによってサイトが紹介料を獲得できる手段を提供することを目的に設定されたアフィリエイト宣伝プログラムである、Amazonアソシエイト・プログラムを利用しています。

app/views/users/_title.html.slim
#title_text class=("#{'edit_title' if user.portfolio_creator?(current_user)}")
  h2.title.text-center = button_tag user.title, id: "btn_title" ,class: "btn-light"
#user-error-message.alert.alert-danger
textarea#edit_area.form-group.mb-30.form-control = user.title
.text-center = button_tag "編集完了", class: "edit_title title_submit btn btn-primary"

app/views/users/index.html.slim
.text-center.mb-4
  h3.portfolios みんなのポートフォリオ
.container-fluid
  table.table.table-hover
    thead
      tr.text-center
        th クリエイター
        th タイトル
        th 最新ポートフォリオ
    = render partial: 'shared/user_template', collection: @contents_all, as: 'content'
  .index_footer
    = paginate @contents_all

app/views/users/show.html.slim
.main
  .portfolio_title data-intro=("クリックして好きなタイトルに変更しよう！") data-step="2"
    = render 'title', user: @user
  .portfolio_menu
    .viewed_user
      = link_to sns_account_link(@user.twitter_url), target: '_new' do
        = image_tag @user.twitter_icon, class: 'rounded_circle' unless @user.portfolio_creator?(current_user)
    .twitter_share data-intro=("設定が終わったらツイッターでシェアしよう!!") data-step="3"
      = render 'shared/share_button'
    - if @user.portfolio_creator?(current_user)
      .tutorial
        = button_tag "使い方", class: "btn btn-info"
  .portfolio_all
    ul id=("#{'sortable' if @user.portfolio_creator?(current_user)}") data-intro=("各画像の左上のボタンから検索画面に移動し商品を設定しよう。スライドすると位置を交換できる。") data-step="1"
      - @contents.each do |content|
        li.photo id="#{content.position}" class=("#{'hvr-curl-top-left' if @user.portfolio_creator?(current_user)}") style="background-image:url(#{content.content_img})"
          = link_to content.create_link, class: "material", target: "#{ '_new' if content.amazon_link.present? }" do
          - if @user.portfolio_creator?(current_user)
            = link_to edit_user_content_path(content.user_id, content.position) do
              i.fa.fa-pencil-square-o.fa-5x
    = javascript_include_tag "show.js"